sudo: false
cache:
  bundler: true
language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.12.5
script: bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: "mBGWs5QFmmspHjc+qNywVywwu16KUT0GNqeSasAC3I8JraNTk7NDqOM9HBix67WaPvrY7t3qXTXi52pXhYciyV4tkqBSD5b8TreXQA/ABpvkZvGrbbBjfjHHZ7D0ilmmxnR1ygR07T0ozSvtWIrymOTbhQFfU7sGLwexn4ve7z0fWJEyMGcQJPA5h7gJmUtjgeTc0IO3Et4B8yiIIqdLs0zFRMAPx2WOeKJhaHHEvByViQsfuMsBxzbRrD6MTRqfMVSEPp5dAis0bdycbgwqJ9EEbtvEafBK5fmnbAUJmB6UI8HZ5pP6W7Z3Vz/br2h2LKOOlg7DvCFnDnG9sqT4wdVrjW1l7y6nNSKvtl8U3/Y4kjGPooBC8+tM574ym67KRRhZW4OgDh5bEc96dbpmCnrLZPjC6sDQkwro0VGZhCTqqkJ/pmVyrxKDHtY+fjcxL9vCNAobgKi0ribH65+SpE8/Y99CMxT4zSoCtyT1EwA4RK9JH1GGU2tndwev6NRGzoc14NwbwWihCsKBYxdc8Rl1IRX3DLxgOHT3NTeMhq7jQxlrypePajuqEdWeFVS0tK3unB01blW4IS7fWA7wAaV4+s5ao/OxhP3OEEORTxvq3dchnxvmGLoH8LdQS3pW93KYeZENACtJRLBghoLbkDGgLlG/Qjz5o+cfD520NGY="
  gem: ncypher
  on:
    tags: true
    repo: pcboy/ncypher
